image:
    name: aus-gitlab.local.tenstorrent.com:5005/riscv/dv/mem-manager/mem-manager:c0f23d5b805db6b377d1ec5b1eb7e53315871cf6cdb0cbd4769255c14ba1e210

stages:
    - test

test:
    stage: test
    script:
        - bazel --output_user_root=./bazel_output_user_root test test:all --test_output=all
